# Generated by Django 4.2.7 on 2023-11-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPP', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
